export const CATEGORIES=[
{id:"customers",title:"Clientes y página web",icon:"◎",color:"#7157d9",description:"Cómo informas, vendes y recoges datos por Internet."},
{id:"privacy",title:"Datos personales",icon:"◇",color:"#137b68",description:"Qué datos guardas, por qué y durante cuánto tiempo."},
{id:"people",title:"Equipo y organización",icon:"○",color:"#d2693c",description:"Personas, normas internas y canales de confianza."},
{id:"suppliers",title:"Proveedores",icon:"↗",color:"#3374bd",description:"Quién accede a tu información y con qué garantías."},
{id:"security",title:"Seguridad y continuidad",icon:"✦",color:"#bb8b18",description:"Cómo reduces el riesgo de perder datos o sufrir un incidente."}];
export const CONTROLS=[
{id:"privacy_notice",category:"customers",question:"Cuando alguien rellena un formulario, ¿le explicáis para qué usaréis sus datos?",help:"Por ejemplo, junto al formulario de contacto, presupuesto o suscripción aparece un texto de privacidad comprensible.",weight:7,action:"Añade información de privacidad breve y visible a cada formulario.",why:"Las personas deben saber quién usa sus datos, para qué y cómo ejercer sus derechos."},
{id:"cookies",category:"customers",question:"¿La web permite rechazar las cookies tan fácilmente como aceptarlas?",help:"Si usáis analítica, publicidad o vídeos externos, debe existir una elección real.",weight:7,action:"Revisa el aviso de cookies y ofrece aceptar, rechazar y configurar con la misma claridad.",why:"Instalar cookies no necesarias sin una elección válida puede generar reclamaciones."},
{id:"legal_web",category:"customers",question:"¿La web dice claramente quién está detrás del negocio?",help:"Busca un aviso legal con nombre o razón social, NIF, domicilio y una forma directa de contacto.",weight:5,action:"Publica o completa el aviso legal con los datos identificativos del negocio.",why:"Quien visita o compra debe poder identificar al prestador del servicio."},
{id:"online_sales",category:"customers",question:"Si vendéis online, ¿se ven antes de pagar el precio final, devoluciones y condiciones?",help:"Marca «No aplica» si no vendéis ni contratáis servicios por Internet.",weight:6,action:"Haz visibles condiciones, precio total, plazos y devoluciones antes del pago.",why:"Una compra informada reduce conflictos y protege al cliente y al negocio."},
{id:"data_map",category:"privacy",question:"¿Sabéis qué datos personales guardáis y en qué lugares están?",help:"Piensa en clientes, empleados y proveedores dentro de correos, Excel, móviles, nube, facturación o CRM.",weight:8,action:"Haz una lista sencilla de los datos, para qué se usan, dónde están y quién accede.",why:"No se puede proteger ni borrar correctamente una información que no está localizada."},
{id:"lawful_use",category:"privacy",question:"¿Tenéis claro por qué podéis usar cada dato personal?",help:"Puede ser por un contrato, obligación legal, consentimiento u otro motivo válido; no todo necesita consentimiento.",weight:7,action:"Relaciona cada uso de datos con su finalidad y una base jurídica válida.",why:"Guardar un dato no autoriza a utilizarlo para cualquier propósito."},
{id:"retention",category:"privacy",question:"¿Borráis los datos cuando dejan de ser necesarios?",help:"Por ejemplo, existe una regla para eliminar candidaturas, antiguos contactos o documentación fuera de plazo.",weight:5,action:"Define plazos de conservación y un calendario sencillo de revisión y borrado.",why:"Acumular datos antiguos aumenta el impacto de errores y filtraciones."},
{id:"rights",category:"privacy",question:"¿Sabríais responder si alguien pide ver o borrar sus datos?",help:"Debe haber una persona responsable y un método para localizar la información y contestar a tiempo.",weight:5,action:"Crea un procedimiento breve para recibir y responder solicitudes de derechos.",why:"Las personas pueden solicitar acceso, rectificación, supresión y otros derechos."},
{id:"confidentiality",category:"people",question:"¿El equipo sabe qué información es confidencial y cómo debe tratarla?",help:"Sirven instrucciones claras, formación breve y compromisos de confidencialidad.",weight:6,action:"Entrega pautas prácticas de confidencialidad y seguridad a todo el equipo.",why:"Muchos incidentes nacen de errores cotidianos, no de ataques sofisticados."},
{id:"access_offboarding",category:"people",question:"Cuando alguien cambia de puesto o se marcha, ¿revisáis sus accesos?",help:"Correo, aplicaciones, carpetas, cuentas y contraseñas deben actualizarse con rapidez.",weight:6,action:"Usa una lista de altas, cambios y bajas para conceder y retirar accesos.",why:"Las cuentas olvidadas son una puerta de entrada frecuente."},
{id:"reporting",category:"people",question:"¿Existe una forma segura de avisar sobre irregularidades sin miedo?",help:"Para empresas de 50 o más personas suele ser obligatorio un sistema interno. En empresas menores puede ser una buena práctica.",weight:6,action:"Con 50 o más personas, valida urgentemente el sistema interno; si no, define un canal de confianza.",why:"Detectar problemas pronto permite corregirlos y protege a quien informa."},
{id:"processor_contracts",category:"suppliers",question:"¿Hay acuerdos de protección de datos con gestoría, informática, nube y otros proveedores?",help:"Importa especialmente cuando un tercero puede ver datos de clientes o del equipo.",weight:7,action:"Identifica proveedores con acceso a datos y firma el acuerdo correspondiente.",why:"Aunque otra empresa gestione los datos, tu negocio conserva responsabilidades."},
{id:"supplier_review",category:"suppliers",question:"¿Comprobáis mínimamente a un proveedor antes de darle información?",help:"Por ejemplo, revisáis seguridad, ubicación de datos, subcontratación y borrado final.",weight:5,action:"Crea una comprobación básica antes de contratar servicios que manejen información.",why:"Un proveedor inseguro puede trasladar su riesgo a tu empresa."},
{id:"passwords",category:"security",question:"¿Cada persona usa su propia cuenta, contraseñas únicas y doble factor?",help:"Evita cuentas compartidas. Activa el segundo factor en correo, nube, banca y administración.",weight:7,action:"Activa doble factor y elimina cuentas compartidas en los servicios críticos.",why:"Una contraseña robada no debería bastar para entrar en la empresa."},
{id:"backups",category:"security",question:"¿Tenéis copias de seguridad que se prueban de vez en cuando?",help:"Una copia útil está separada del equipo principal y se ha comprobado que puede recuperarse.",weight:7,action:"Automatiza copias separadas y prueba una recuperación.",why:"Una copia nunca restaurada puede fallar cuando más se necesita."},
{id:"updates",category:"security",question:"¿Ordenadores, móviles y programas se actualizan con regularidad?",help:"Incluye sistema, navegador, tienda online, plugins, antivirus, router y dispositivos.",weight:6,action:"Activa actualizaciones automáticas y revisa mensualmente lo pendiente.",why:"Las actualizaciones corrigen fallos conocidos que aprovechan muchos ataques."},
{id:"incident_plan",category:"security",question:"¿Sabríais a quién llamar y qué hacer si perdéis datos o sufrís un ataque?",help:"Un plan básico indica cómo aislar el problema, conservar pruebas y recuperar el servicio.",weight:6,action:"Escribe una hoja de respuesta con contactos, primeros pasos y responsables.",why:"Las primeras horas son decisivas para limitar daños y cumplir plazos."}];
const VALUE={yes:1,partial:.5,no:0,na:null};
export function calculateAssessment(answers){const applicable=CONTROLS.filter(c=>VALUE[answers[c.id]]!==null);const possible=applicable.reduce((s,c)=>s+c.weight,0);const earned=applicable.reduce((s,c)=>s+c.weight*(VALUE[answers[c.id]]??0),0);const score=possible?Math.round(earned/possible*100):0;const level=score>=80?"Buena base":score>=55?"Hay trabajo en marcha":"Conviene actuar";const tone=score>=80?"good":score>=55?"warning":"critical";const gaps=applicable.filter(c=>answers[c.id]!=="yes").sort((a,b)=>b.weight*(1-(VALUE[answers[b.id]]??0))-a.weight*(1-(VALUE[answers[a.id]]??0)));const categories=CATEGORIES.map(cat=>{const controls=applicable.filter(c=>c.category===cat.id);const max=controls.reduce((s,c)=>s+c.weight,0);const got=controls.reduce((s,c)=>s+c.weight*(VALUE[answers[c.id]]??0),0);return{...cat,score:max?Math.round(got/max*100):null}});return{score,level,tone,gaps,categories}}
function card(c,i){const opts=[["yes","Sí, lo tenemos"],["partial","A medias / no estoy seguro"],["no","No, todavía no"],["na","No aplica"]];return `<article class="question-card"><div class="question-number">${String(i+1).padStart(2,"0")}</div><div class="question-body"><h4>${c.question}</h4><p>${c.help}</p><div class="answer-options" role="radiogroup" aria-label="${c.question}">${opts.map(([v,l])=>`<label><input type="radio" name="${c.id}" value="${v}" required><span>${l}</span></label>`).join("")}</div></div></article>`}
function renderSteps(){const box=document.querySelector("#question-steps");CATEGORIES.forEach((cat,n)=>{const s=document.createElement("section");s.className="form-step";s.dataset.step=n+1;s.innerHTML=`<div class="step-intro"><span class="step-icon" style="--accent:${cat.color}">${cat.icon}</span><div><p class="category-label">Área ${n+1} de ${CATEGORIES.length}</p><h3>${cat.title}</h3><p>${cat.description}</p></div></div>${CONTROLS.filter(c=>c.category===cat.id).map(card).join("")}`;box.appendChild(s)})}
const color=s=>s>=80?"good":s>=55?"warning":"critical";
function renderResult(org,sector,employees,a){const r=document.querySelector("#result"),p=a.gaps.slice(0,5);r.className=`result ${a.tone}`;r.innerHTML=`<div class="result-hero"><div><p class="kicker">Tu primera hoja de ruta</p><h2>${org}</h2><p>${sector} · ${employees} personas</p></div><div class="score-ring" style="--score:${a.score}"><div><strong>${a.score}</strong><small>sobre 100</small></div></div></div><div class="result-summary"><span>${a.level}</span><p>${a.score>=80?"Hay una base consistente. Ahora toca comprobar evidencias y mantenerla al día.":a.score>=55?"Ya existen medidas útiles, pero algunas brechas merecen atención para evitar sustos.":"No significa que todo esté mal: ya sabes por dónde empezar. Prioriza estos pasos."}</p></div><div class="result-grid"><section><h3>Tu mapa por áreas</h3><div class="area-scores">${a.categories.filter(c=>c.score!==null).map(c=>`<div><span><i style="background:${c.color}"></i>${c.title}<b>${c.score}%</b></span><div><i class="${color(c.score)}" style="width:${c.score}%"></i></div></div>`).join("")}</div></section><section class="next-actions"><h3>Empieza por aquí</h3><ol>${p.map((x,i)=>`<li><b>${i+1}</b><div><span>${x.action}</span><p>${x.why}</p></div></li>`).join("")}</ol></section></div><div class="result-footer"><div><strong>Importante</strong><p>El resultado se basa en lo que has indicado. Confirmar el cumplimiento requiere evidencias y, cuando proceda, asesoramiento profesional.</p></div><button id="print-result" class="secondary" type="button">Imprimir resultado</button></div>`;r.hidden=false;r.scrollIntoView({behavior:"smooth",block:"start"});document.querySelector("#print-result").onclick=()=>window.print()}
if(typeof document!=="undefined"){renderSteps();const form=document.querySelector("#assessment-form"),steps=[...document.querySelectorAll(".form-step")],next=document.querySelector("#next"),back=document.querySelector("#back"),submit=document.querySelector("#submit");let current=0;function show(i){current=i;steps.forEach((s,n)=>s.classList.toggle("active",n===i));back.hidden=i===0;next.hidden=i===steps.length-1;submit.hidden=i!==steps.length-1;document.querySelector("#progress-label").textContent=i===0?"Contexto de la empresa":CATEGORIES[i-1].title;document.querySelector("#progress-count").textContent=`Paso ${i+1} de ${steps.length}`;document.querySelector("#progress-bar").style.width=`${(i+1)/steps.length*100}%`;document.querySelector("#diagnostico").scrollIntoView({behavior:"smooth",block:"start"})}function valid(){for(const f of steps[current].querySelectorAll("input,select"))if(!f.checkValidity()){f.reportValidity();return false}return true}next.onclick=()=>{if(valid())show(current+1)};back.onclick=()=>show(current-1);form.onsubmit=e=>{e.preventDefault();if(!valid())return;const d=new FormData(form),answers=Object.fromEntries(CONTROLS.map(c=>[c.id,d.get(c.id)]));renderResult(d.get("organization").trim(),d.get("sector"),d.get("employees"),calculateAssessment(answers))};document.querySelector("#reset").onclick=()=>{form.reset();document.querySelector("#result").hidden=true;show(0);document.querySelector("#organization").focus()};show(0)}
